### ISSUE TITLE
Download Links in the run_jupyter.sh fail

### ISSUE THREAD

**Issue by OniDaito** [NICALab/3DM#1]
The following links don't appear to work any more:

https://drive.google.com/uc?id=1kUtX1977ly9Kj5sdpcVl_lMPmwQTXlpN
and
https://drive.google.com/uc?id=1gmi_bjMFJ-0dfAHURKrhI15W7VQmXpmZ

So I can't successfully run the example. Is this data still available somewhere please?
Cheers
B

**Comment by SteveJayH** [comment]
Sorry for the inconvenience and thanks for let us know.

We've updated the run_jupyter.sh files with working GDrive links.
We've checked it is working now, but please let us know if you have any problem.

Sincerely,
Seungjae Han

**Comment by OniDaito** [comment]
Wow! That was fast! Thank-you very much. I shall give it a go now.
Cheers
Ben
